CREATE TABLE IF NOT EXISTS STUDENT (
    ROLL_NO VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255),
    PHONE VARCHAR(255),
    AGE INTEGER
);


INSERT INTO STUDENT (ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
    ('1', 'RAM', 'DELHI','*****',18),
    ('2', 'RAMESH', 'DELHI','*****',18),
    ('3', 'SUJIT', 'MUMBAI','*****',20),
    ('4', 'SURESH', 'GURGAON','*****',18),
    ('5', 'PRIYA', 'SEOUL','*****',20),
    ('6', 'ANKITA', 'GURGAON','*****',18);


SELECT * FROM STUDENT;

SELECT * FROM  STUDENT WHERE AGE = 18 AND ADDRESS = "GURGAON";

SELECT * FROM  STUDENT WHERE AGE = 18 AND NAME = "RAM";

SELECT * FROM  STUDENT WHERE NAME = "SUJIT" OR NAME = "RAM";

SELECT * FROM  STUDENT WHERE NAME = "RAMESH" OR AGE = 20;

SELECT * FROM  STUDENT WHERE AGE = 18 AND (NAME = "PRIYA" OR NAME = "ANKITA");